Add auth token to ClientOptions
frida/frida-web-client pull request #1
Opened 2024-09-11 22:53 UTC by ChiChou

Support frida-server `--token` option

2024-09-11 23:28 UTC, ChiChou commented
Looks like https://github.com/frida/node-dbus-next only used the parser logic from upstream.
The upstream repo looks dead, I would like to contribute a library for the same api but in typescript

2024-09-15 11:47 UTC, oleavr commented
Thanks! That would be awesome by the way.

I accidentally un-drafted this -- please let me know when it's ready to be merged 😊

2024-09-23 11:28 UTC, ChiChou commented
🙌 for this PR it's ready to be merged, thanks

I am planning to port more interfaces. That's gonna be more future work

2024-10-01 16:23 UTC, oleavr requested changes
Thanks! :raised_hands: (And apologies for the delay here!)

2024-10-01 16:23 UTC, oleavr commented on lib/client.ts
> +        if (typeof options.token === "string") {
```suggestion
        if (options.token !== undefined) {
```

Would be good to use a strict check here.

2024-10-18 22:13 UTC, merged

2024-10-18 22:15 UTC, oleavr commented
Just released this in `@frida/web-client@3.1.0` :tada: